[window]
decorations = "Full"
opacity = 0.9
blur = true
padding = { x = 4, y = 4 }

[font]
normal = { family = "UDEV Gothic NF", style = "Regular" }
builtin_box_drawing = false
size = 14

[selection]
save_to_clipboard = true

[terminal]
shell = { program = "nu" }
osc52 = "CopyPaste"
