$env.PROMPT_COMMAND | print
export-env {
    load-env {
        TRANSIENT_PROMPT_COMMAND: $env.PROMPT_COMMAND
#  TRANSIENT_PROMPT_COMMAND_RIGHT: $env.PROMPT_COMMAND_RIGHT
#  TRANSIENT_PROMPT_INDICATOR: $env.PROMPT_INDICATOR
#  TRANSIENT_PROMPT_INDICATOR_VI_NORMAL: $env.PROMPT_INDICATOR_VI_NORMAL
#  TRANSIENT_PROMPT_INDICATOR_VI_INSERT: $env.PROMPT_INDICATOR_VI_INSERT
#  TRANSIENT_PROMPT_MULTILINE_INDICATOR: $env.PROMPT_MULTILINE_INDICATOR
    }
}
# $env.PROMPT_COMMAND = null
