[restic.defaults]
retry_lock = "30m"
keep_daily = 7
keep_weekly = 5
keep_monthly = 12
keep_yearly = 3
check_read_data_subset = "5%"
randomized_delay = "1h"

[restic.hosts.cristina]
enabled = true
backup_calendar = "*-*-* 03:00:00"
maintenance_calendar = "Sun *-*-* 05:00:00"
check_calendar = "*-*-01 07:00:00"
