[packages.windows.winget]
# TOOD: Intel.IntelDriverAndSupportAssistant if platform is Intel based (not AMD)
essentials = [
    "gerardog.gsudo",
    "AutoHotkey.AutoHotkey",
    "Zen-Team.Zen-Browser",
    "Zoom.Zoom",
    "Dropbox.Dropbox",
    "AgileBits.1Password",
    "AgileBits.1Password.CLI",
    "Discord.Discord",
    "Microsoft.PowerToys",
    "SlackTechnologies.Slack",
#    "Nushell.Nushell",
#    "Starship.Starship",
#    "Helix.Helix",
    "Obsidian.Obsidian",
    "Wakatime.DesktopWakatime",
#    "rsteube.Carapace",
    "REALiX.HWiNFO",
    "RamenSoftware.Windhawk",
    "SteelSeries.GG",
#    "ajeetdsouza.zoxide",
]
gaming = [
    "Valve.Steam",
]
development = [
    "Docker.DockerDesktop",
    "JetBrains.Toolbox",
    "jdx.mise",
    "Git.Git",
#    "GitHub.cli",
#    "tamasfe.taplo",
    "Microsoft.VisualStudioCode",
    "Alacritty.Alacritty",
    "Microsoft.VisualStudio.2022.BuildTools",
]