
[packages.windows.winget]
list = """
AutoHotkey.AutoHotkey
Docker.DockerDesktop
Zoom.Zoom
Google.Chrome
Dropbox.Dropbox
AgileBits.1Password
AgileBits.1Password.CLI
Discord.Discord
JetBrains.Toolbox
Bandisoft.Honeyview
Microsoft.PowerToys
SlackTechnologies.Slack
Nushell.Nushell
Starship.Starship
Helix.Helix
Obsidian.Obsidian
jdx.mise
CharlesMilette.TranslucentTB
Wakatime.DesktopWakatime
Git.Git
GitHub.cli
Amazon.AWSCLI
tamasfe.taplo
jqlang.jq
rsteube.Carapace
Anysphere.Cursor
Microsoft.VisualStudioCode
Google.GoogleDrive
"""
# VB-Audio.Voicemeeter.Potato