[packages.windows.winget]
# TOOD: Intel.IntelDriverAndSupportAssistant if platform is Intel based (not AMD)
essentials = [
    "AutoHotkey.AutoHotkey",
    "Zen-Team.Zen-Browser",
    "Zoom.Zoom",
    "Dropbox.Dropbox",
    "AgileBits.1Password",
    "AgileBits.1Password.CLI",
    "Discord.Discord",
    "Microsoft.PowerToys",
    "SlackTechnologies.Slack",
    "Obsidian.Obsidian",
    "Wakatime.DesktopWakatime",
    "REALiX.HWiNFO",
    "RamenSoftware.Windhawk",
    "SteelSeries.GG",
]
gaming = [
    "Valve.Steam",
]
development = [
    "Docker.DockerDesktop",
    "JetBrains.Toolbox",
    "Git.Git",
    "Microsoft.VisualStudioCode",
    "Alacritty.Alacritty",
    "Microsoft.VisualStudio.2022.BuildTools",
]