[packages.windows.winget]
# TOOD: Intel.IntelDriverAndSupportAssistant if platform is Intel based (not AMD)
essentials = [
    "gerardog.gsudo",
    "AutoHotkey.AutoHotkey",
    "Zoom.Zoom",
    "Dropbox.Dropbox",
    "AgileBits.1Password",
    "AgileBits.1Password.CLI",
    "Discord.Discord",
    "Bandisoft.Honeyview",
    "Microsoft.PowerToys",
    "SlackTechnologies.Slack",
    "Nushell.Nushell",
    "Starship.Starship",
    "Helix.Helix",
    "Obsidian.Obsidian",
    "CharlesMilette.TranslucentTB",
    "Wakatime.DesktopWakatime",
    "rsteube.Carapace",
    "REALiX.HWiNFO",
    "RamenSoftware.Windhawk",
]
gaming = [
    "Valve.Steam",
]
development = [
    "Docker.DockerDesktop",
    "JetBrains.Toolbox",
    "jdx.mise",
    "Git.Git",
    "GitHub.cli",
    "tamasfe.taplo",
    "Anysphere.Cursor",
    "Microsoft.VisualStudioCode",
    "wez.wezterm",
    "Alacritty.Alacritty",
]