["theme.toml"]
    type = "file"
    url = "https://raw.githubusercontent.com/catppuccin/yazi/refs/heads/main/themes/mocha/catppuccin-mocha-mauve.toml"
    refreshPeriod = "168h"

["Catppuccin-mocha.tmTheme"]
    type = "file"
    url = "https://raw.githubusercontent.com/catppuccin/bat/refs/heads/main/themes/Catppuccin%20Mocha.tmTheme"
    refreshPeriod = "168h"
