tap "jandedobbeleer/oh-my-posh"

brew "carapace"
brew "gh"
brew "git"
brew "gnupg"
brew "jq"
brew "starship"
brew "xz"
brew "jandedobbeleer/oh-my-posh/oh-my-posh"

if OS.mac?
  brew "pinentry-mac"
  mas "1Password", id: 443_987_910
  cask "1password-cli"
  cask "karabiner-elements"
end
