[dms]
image=ghcr.io/atty303/arch-toolbox-paru
pull=true
volume=/run/dbus/system_bus_socket:/run/dbus/system_bus_socket
exported_bins="/usr/bin/dms /usr/bin/dms-greeter /usr/bin/dgop /usr/bin/dsearch"
additional_flags="--userns keep-id:size=65534 --annotation run.oci.keep_original_groups=0"
# Install scroll from AUR
init_hooks=sudo -H -u builder paru -S dms-shell-bin greetd-dms-greeter-git dsearch-bin vulkan-headers quickshell-git cups-pk-helper kimageformats matugen cava pipewire-jack khal fprintd sway --noconfirm;
# Enable host's uwsm to be executable from within the container
# Since environment variables exposed to the host side must be explicitly specified, execute host-spawn directly instead of distrobox-host-exec
init_hooks=echo "#!/bin/sh" >/usr/local/bin/uwsm;
init_hooks=echo "distrobox-host-exec true" >>/usr/local/bin/uwsm;
init_hooks=echo "exec host-spawn --env DISPLAY,SWAYSOCK,I3SOCK,SCROLLSOCK,WAYLAND_DISPLAY,XCURSOR_SIZE,XCURSOR_THEME uwsm \"\$@\"" >>/usr/local/bin/uwsm;
init_hooks=chmod +x /usr/local/bin/uwsm;
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/ghostty

[dms-nvidia]
include=dms
nvidia=true
