[wallpaperengine]
image=ghcr.io/atty303/arch-toolbox-paru
pull=true
nvidia=true
#volume=/run/dbus/system_bus_socket:/run/dbus/system_bus_socket
#volume=/run/user/1000/X11-unix:/tmp/.X11-unix
exported_bins="/usr/bin/linux-wallpaperengine"
# TODO: /usr/share/man, /usr/share/wayland-sessions, /usr/share/icons, /usr/share/bash-completions
#additional_packages="base-devel"
# Install scroll from AUR
init_hooks=sudo -H -u builder paru -S wayland-protocols linux-wallpaperengine-git --noconfirm;
