min_version = "2025.9.2"

[tools]
age = "latest"
bat = "latest"
bun = "latest"
carapace = "latest"
claude = "latest"
deno = "latest"
fzf = "latest"
github-cli = "latest"
helix = "latest"
taplo = "latest"
restic = "latest"
ripgrep = "latest"
starship = "latest"
zellij = { version = "latest", os = ["linux", "macos"] }
zoxide = "latest"

"aqua:nushell/nushell" = "latest"
"ubi:open-source-cooperative/keyring-rs" = "latest"

[tools."http:gitpod-cli"]
version = "stable"
[tools."http:gitpod-cli".platforms]
linux-x64 = { url = "https://releases.gitpod.io/cli/stable/gitpod-linux-amd64" }
linux-arm64 = { url = "https://releases.gitpod.io/cli/stable/gitpod-linux-arm64" }
macos-x64 = { url = "https://releases.gitpod.io/cli/stable/gitpod-darwin-amd64" }
macos-arm64 = { url = "https://releases.gitpod.io/cli/stable/gitpod-darwin-arm64" }
windows-x64 = { url = "https://releases.gitpod.io/cli/stable/gitpod-windows-amd64.exe" }
windows-arm64 = { url = "https://releases.gitpod.io/cli/stable/gitpod-windows-arm64.exe" }

[settings]
activate_aggressive = true
default_config_filename = ".mise.toml"
experimental = true
windows_default_file_shell_args = "pwsh.exe -NoLogo -NoProfile -ExecutionPolicy Bypass"
windows_default_inline_shell_args = "pwsh.exe -NoLogo -NoProfile -ExecutionPolicy Bypass -Command"
windows_shim_mode = "symlink"

npm.bun = true

python.uv_venv_auto = true
