min_version = "2025.9.2"

[tools]
age = "latest"
bun = "latest"
carapace = "latest"
claude = "latest"
deno = "latest"
fzf = "latest"
github-cli = "latest"
helix = "latest"
taplo = "latest"
node = "latest"
restic = "latest"
starship = "latest"
zellij = { version = "latest", os = ["linux", "macos"] }
zoxide = "latest"

"aqua:nushell/nushell" = "latest"
"ubi:open-source-cooperative/keyring-rs" = "latest"

[tools."aqua:atuinsh/atuin"]
version = "latest"
os = ["linux", "macos"]

[tools."github:Esgariot/atuin-win"]
version = "18.8.0"
os = ["windows"]
platforms.windows-x64.asset_pattern = "atuin.exe"

[settings]
activate_aggressive = true
default_config_filename = ".mise.toml"
experimental = true
windows_default_file_shell_args = "pwsh.exe -NoLogo -NoProfile -ExecutionPolicy Bypass"
windows_default_inline_shell_args = "pwsh.exe -NoLogo -NoProfile -ExecutionPolicy Bypass -Command"
windows_shim_mode = "symlink"

npm.bun = true

python.uv_venv_auto = true
