[bootstrap.packages]
"brew:pinentry-mac" = "latest"
"brew-cask:1password-cli" = "latest"
"brew-cask:google-japanese-ime" = "latest"
"brew-cask:karabiner-elements" = "latest"
"brew-cask:raycast" = "latest"
"brew-cask:visual-studio-code" = "latest"

[bootstrap.macos.launchd.agents.gui-path]
program = "/bin/sh"
args = ["-c", "/bin/launchctl setenv PATH \"$HOME/.local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin:/opt/homebrew/sbin\""]
run_at_load = true
kickstart = true
