[tools]
node = "lts"
usage = "latest"

# clang
# cmake
# ninja

#[env]
#_.python.venv = { path = "{{ xdg_state_home }}/venv/default", create = true }

[settings]
default_config_filename = ".mise.toml"
experimental = true
windows_shim_mode = "symlink"
#python.default_packages_file = "{{ xdg_config_home }}/mise/default-python-packages"
