min_version = "2025.9.2"

[settings]
activate_aggressive = true
experimental = true
windows_default_file_shell_args = "pwsh.exe -NoLogo -NoProfile -ExecutionPolicy Bypass"
windows_default_inline_shell_args = "pwsh.exe -NoLogo -NoProfile -ExecutionPolicy Bypass -Command"
windows_shim_mode = "symlink"

python.uv_venv_auto = true

[settings.github]
oauth_client_id = "Iv1.4e496c43570982f2"
oauth_scopes = ""
oauth_open_browser = true
oauth_export_env = ""
