[tools]
age = "latest"
carapace = "latest"
claude = "latest"
fzf = "latest"
github-cli = "latest"
helix = "latest"
taplo = "latest"
node = "latest"
starship = "latest"
zoxide = "latest"

"aqua:nushell/nushell" = "latest"

"ubi:open-source-cooperative/keyring-rs" = "latest"

[settings]
default_config_filename = ".mise.toml"
experimental = true
windows_shim_mode = "symlink"
